version: 2.1
executors:
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      NUGET_XMLDOC_MODE: skip
      BUILD_CONFIG: Release
  docker-in-docker:
    docker:
      - image: docker:17.09.0-ce-git
    environment:
      OWNER: guitarrapc
      IMAGE_NAME: agonespod
jobs:
  build-test:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet build -c Debug
      # todo: add test
      # - run: dotnet tool install -g dotnet-reportgenerator-globaltool
      # - run: x=$(dotnet test -c Debug --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Include=[AgonesPod.*]*); echo $x;
      # - run: curl -s https://codecov.io/bash > codecov
      # - run: chmod +x codecov
      # - run: ./codecov -f ./tests/AgonesPod.Tests/coverage.opencover.xml
  build-push:
    executor: dotnet
    steps:
      - checkout
      - run:
          name: deploy when exists tag
          command: |
            if [ "${CIRCLE_TAG-undefined}" != "undefined" ]; then
              dotnet build -c Release -p:Version=${CIRCLE_TAG}
              # x=$(dotnet test -c Release --no-build); echo $x;
              dotnet pack ./src/AgonesPod/AgonesPod.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
              dotnet nuget push ./src/AgonesPod/bin/Release/AgonesPod.${CIRCLE_TAG}.nupkg -s https://www.nuget.org/api/v2/package -k ${NUGET_KEY}
            else
              echo tag not exists
            fi
      - store_artifacts:
          path: ./src/AgonesPod/bin/Release
          destination: ./AgonesPod/
  docker:
    executor: docker-in-docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.09.0-ce
      - run: docker build --build-arg VCS_REF=$(git rev-parse --short HEAD) -t ${OWNER}/${IMAGE_NAME}:latest -f samples/AgonesPod.ConsoleSample/Dockerfile .
      - run: docker tag ${OWNER}/${IMAGE_NAME}:latest ${OWNER}/${IMAGE_NAME}:$CIRCLE_TAG
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run: docker push ${OWNER}/${IMAGE_NAME}
workflows:
  build-and-push:
    jobs:
      - build-test:
          filters:
            tags:
              only: /.*/
      - build-push:
          context: nuget
          filters:
            tags:
              only: /^[0-9](\.[0-9]){2}$/
            branches:
              ignore: /.*/
      - docker:
          context: dockerhub-login
          requires:
            - build-test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
