apiVersion: v1
kind: ServiceAccount
metadata:
  name: agones-rest
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: agones-rest
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - agones.dev
  resources:
  - gameservers
  verbs:
  - list
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: agones-rest
subjects:
- kind: ServiceAccount
  name: agones-rest
  namespace: default
roleRef:
  kind: ClusterRole
  name: agones-rest
  apiGroup: rbac.authorization.k8s.io
